### ISSUE TITLE
[RFC] reducing number of dependencies

### ISSUE THREAD

**Issue by d-e-s-o** [sekey/ssh-agent.rs#16]
I'd like to propose that we check whether we can cut down on the number of dependencies a bit. I see at least three benefits of doing so:
1) Reduced memory foot print: Given that in all likely hood this crate is used to build a daemon which resides in memory for a long time, it seems beneficial to ensure a low foot print.
2) Reduced trusted computing base: Generally speaking more code means more bugs and given that we are likely to work with sensitive key material, we should reduce the projected number of bugs.
3) Decreased maintenance effort for downstream crates: Typically applications are shipped with a `Cargo.lock` file pinning the dependencies in order to ensure reproducible builds. Each dependency increases the maintenance effort for version bumps and possible auditing of changes.
4) Reduced build time. 'Nuff said.

If we want to at least pick the low hanging fruit (and I am not sure how much there is), we can probably check three fronts:
- a) Replace crates: Be that large crates being replaced with smaller ones or with fewer dependencies, or others with hand written code.
- b) Check required features: Some crates come with features that can be disabled and reduce the functionality available. It's possible we don't need it or may not need it after minor massage to the code in question.
- c) Introduce features: some of the functionality could be considered optional on the crate itself and could be enabled conditionally through a feature. Logging is an example: some clients may not care about environment configurable log levels and just want errors dumped to `stderr`. Of course, that has to be balanced with the complexity introduced for managing those (and testing builds).

Do you have an opinion on the matter? I haven't checked much so far. Perhaps there is nothing to gain here. Most of the dependencies are transitive in nature anyway. But I wanted to first check with you on what you think before investing much time into this effort and then pull requests not being accepted.

**Comment by fmpomar** [comment]
I am always in favor of making things as small and simple as possible. I'll take a look at the PRs you sent as soon as I can.

Reducing the dependencies is a good idea as long as we don't lose functionality. If we do lose a bit, maybe we can make it optional with features. For instance, I would like to know if you're using the Agent trait or just taking advantage of the (de)serialization. Making the Agent optional would remove the strict `tokio` dependency, which brings a lot of crates along with it

Also, I didn't really look into the footprint of this library. Can you give us any info on how much binary size and memory use it adds to your project? I assume it must be enough for you to make this proposal, but it doesn't hurt to know.

Thanks!

**Comment by d-e-s-o** [comment]
Thanks for your response. Sounds good! I just wanted clarification. Obviously it is a trade-off and I don't plan to make huge changes.

> Also, I didn't really look into the footprint of this library. Can you give us any info on how much binary size and memory use it adds to your project? I assume it must be enough for you to make this proposal, but it doesn't hurt to know.

Well, "adds" may not be appropriate in this case: the project **is** basically only an agent. That is to say that without your crate there is nothing left :P 

Anyway, when optimized for size, the stripped release binary is 1686896 in size. While that is not a concern in and of itself on most of today's systems, I think the arguments I brought up are valid. I just see it as a necessity to pick long hanging fruit on this front for every project I work on. If there is nothing to cut out I am fine with that.

**Comment by d-e-s-o** [comment]
There is nothing more to discuss from my side right now. Let me close this issue. We can always reopen or take it to individual pull requests. Thanks for your feedback!

**Comment by d-e-s-o** [comment]
I looked into the resulting binary size a bit and the most bloat seems to come from `env_logger` (evidence seems to suggest that its `regex` dependency is pretty big). `env_logger` is not a dependency of `ssh-agent` itself, but I used it because the example did.

Anyway, removing it gets me from 1674720 bytes down to 834944 bytes, which I consider quite significant. That size is already much more reasonable and more in line with my experience.

If I desire further improvement I will probably opt for implementing what the `Agent` trait provides myself (with different means), in which case I may get back to your suggestion of making the actual agent functionality optional to the crate. For now, that is good enough.

**Comment by fmpomar** [comment]
Awesome. Sorry for the delay in answering. It's been a tough week for me!
The size improvement you achieved is really good. As soon as we add a few changes that we needed (a few lines of code, nothing that adds new deps) I'll do another release.
Thanks for all the help!
