### ISSUE TITLE
key_storage example fails for ed25519 key

### ISSUE THREAD

**Issue by d-e-s-o** [sekey/ssh-agent.rs#5]
When I run the `key_storage` example and try adding an ed25519 key, the request always fails.
```
[2019-02-10T15:39:13Z ERROR ssh_agent::agent] Error while handling message; error = Proto(StringEncoding(FromUtf8Error { bytes: [27, 156, 140, 34, 160, 237, 74, 90, 244, 101, 144, 10, 219, 86, 184, 145, 37, 174, 62, 195, 100, 99, 192, 227, 36, 245, 253, 158, 176, 53, 91, 235], error: Utf8Error { valid_up_to: 1, error_len: Some(1) } }))
```

Doing the same with an RSA key works just fine. Any idea what may be wrong? I really fail to understand what the internally used encoding for ed25519 keys is. Why is that a `String` and not a binary blob?

**Comment by fmpomar** [comment]
The description of the SSH Agent Protocol (https://tools.ietf.org/id/draft-miller-ssh-agent-00.html) specifies the field as "string". They probably meant "bytes[]", but I took it literally.
The only difference between using `String` and `Vec<u8>` is that the former performs a UTF-8 decoding, so we should try changing it to the latter.
I'll make this fix ASAP, but you're free to send a PR with this change if this fixes the issue.

Thanks!

**Comment by d-e-s-o** [comment]
No worries, I already got it working with `Vec<u8>` :) I'll send a PR soon.
